
rotor("ETW", "-", "Zählwerk Enigma (Enigma GA260 | Sicherheitsdienst Enigma)", "QWERTZUIOASDFGHJKPYXCVBNML", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ETW", ['A'])
rotor("I", "-", "Zählwerk Enigma (Enigma GA260 | Sicherheitsdienst Enigma)", "RCSPBLKQAUMHWYTIFZVGOJNEXD", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['S', 'U', 'V', 'W', 'Z', 'A', 'B', 'C', 'E', 'F', 'G', 'I', 'K', 'L', 'O', 'P', 'Q'])
rotor("II", "-", "Zählwerk Enigma (Enigma GA260 | Sicherheitsdienst Enigma)", "WCMIBVPJXAROSGNDLZKEYHUFQT", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['S', 'T', 'V', 'Y', 'Z', 'A', 'C', 'D', 'F', 'G', 'H', 'K', 'M', 'N', 'Q'])
rotor("III", "-", "Zählwerk Enigma (Enigma GA260 | Sicherheitsdienst Enigma)", "FVDHZELSQMAXOKYIWPGCBUJTNR", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['U', 'W', 'X', 'A', 'E', 'F', 'H', 'K', 'M', 'N', 'R'])
rotor("UKW", "-", "Zählwerk Enigma (Enigma GA260 | Sicherheitsdienst Enigma)", "IMETCGFRAYSQBZXWLHKDVUPOJN", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "UKW", ['A'])

rotor("ETW", "-", "Zählwerk Enigma (Enigma GA111 | Hungarian Army Enigma)", "QWERTZUIOASDFGHJKPYXCVBNML", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ETW", ['A'])
rotor("I", "-", "Zählwerk Enigma (Enigma GA111 | Hungarian Army Enigma)", "WLRHBQUNDKJCZSEXOTMAGYFPVI", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['S', 'U', 'V', 'W', 'Z', 'A', 'B', 'C', 'E', 'F', 'G', 'I', 'K', 'L', 'O', 'P', 'Q'])
rotor("II", "-", "Zählwerk Enigma (Enigma GA111 | Hungarian Army Enigma)", "TFJQAZWMHLCUIXRDYGOEVBNSKP", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['S', 'T', 'V', 'Y', 'Z', 'A', 'C', 'D', 'F', 'G', 'H', 'K', 'M', 'N', 'Q'])
rotor("V", "-", "Zählwerk Enigma (Enigma GA111 | Hungarian Army Enigma)", "QTPIXWVDFRMUSLJOHCANEZKYBG", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['S', 'W', 'Z', 'F', 'H', 'M', 'Q'])
rotor("UKW", "-", "Zählwerk Enigma (Enigma GA111 | Hungarian Army Enigma)", "IMETCGFRAYSQBZXWLHKDVUPOJN", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "UKW", ['A'])

rotor("ETW", "-", "Enigma T (Tirpitz)", "KZROUQHYAIGBLWVSTDXFPNMCJE", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ETW", ['A'])
rotor("I", "-", "Enigma T (Tirpitz)", "KPTYUELOCVGRFQDANJMBSWHZXI", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['W', 'Z', 'E', 'K', 'Q'])
rotor("II", "-", "Enigma T (Tirpitz)", "UPHZLWEQMTDJXCAKSOIGVBYFNR", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['W', 'Z', 'F', 'L', 'R'])
rotor("III", "-", "Enigma T (Tirpitz)", "QUDLYRFEKONVZAXWHMGPJBSICT", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['W', 'Z', 'E', 'K', 'Q'])
rotor("IV", "-", "Enigma T (Tirpitz)", "CIWTBKXNRESPFLYDAGVHQUOJZM", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['W', 'Z', 'F', 'L', 'R'])
rotor("V", "-", "Enigma T (Tirpitz)", "UAXGISNJBVERDYLFZWTPCKOHMQ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['Y', 'C', 'F', 'K', 'R'])
rotor("VI", "-", "Enigma T (Tirpitz)", "XFUZGALVHCNYSEWQTDMRBKPIOJ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['X', 'E', 'I', 'M', 'Q'])
rotor("VII", "-", "Enigma T (Tirpitz)", "BJVFTXPLNAYOZIKWGDQERUCHSM", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['Y', 'C', 'F', 'K', 'R'])
rotor("VIII", "-", "Enigma T (Tirpitz)", "YMTPNZHWKODAJXELUQVGCBISFR", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['X', 'E', 'I', 'M', 'Q'])
rotor("UKW", "-", "Enigma T (Tirpitz)", "GEKPBTAUMOCNILJDXZYFHWVQSR", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "UKW", ['A'])

rotor("ETW", "-", "Enigma K (Swiss Commercial)", "QWERTZUIOASDFGHJKPYXCVBNML", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ETW", ['A'])
rotor("I", "-", "Enigma K (Swiss Commercial)", "LPGSZMHAEOQKVXRFYBUTNICJDW", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['Y'])
rotor("II", "-", "Enigma K (Swiss Commercial)", "SLVGBTFXJQOHEWIRZYAMKPCNDU", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['E'])
rotor("III", "-", "Enigma K (Swiss Commercial)", "CJGDPSHKTURAWZXFMYNQOBVLIE", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['N'])
rotor("UKW", "-", "Enigma K (Swiss Commercial)", "IMETCGFRAYSQBZXWLHKDVUPOJN", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "UKW", ['A'])

rotor("ETW", "-", "Enigma K (Swiss Air Force)", "QWERTZUIOASDFGHJKPYXCVBNML", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ETW", ['A'])
rotor("I", "-", "Enigma K (Swiss Air Force)", "PEZUOHXSCVFMTBGLRINQJWAYDK", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['Y'])
rotor("II", "-", "Enigma K (Swiss Air Force)", "ZOUESYDKFWPCIQXHMVBLGNJRAT", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['E'])
rotor("III", "-", "Enigma K (Swiss Air Force)", "EHRVXGAOBQUSIMZFLYNWKTPDJC", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['N'])
rotor("UKW", "-", "Enigma K (Swiss Air Force)", "IMETCGFRAYSQBZXWLHKDVUPOJN", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "UKW", ['A'])

rotor("ETW", "-", "Enigma Railway (Rocket)", "QWERTZUIOASDFGHJKPYXCVBNML", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "ETW", ['A'])
rotor("I", "-", "Enigma Railway (Rocket)", "JGDQOXUSCAMIFRVTPNEWKBLZYH", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['Y'])
rotor("II", "-", "Enigma Railway (Rocket)", "NTZPSFBOKMWRCJDIVLAEYUXHGQ", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['E'])
rotor("III", "-", "Enigma Railway (Rocket)", "JVIUBHTCDYAKEQZPOSGXNRMWFL", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "NORMAL", ['N'])
rotor("UKW", "-", "Enigma Railway (Rocket)", "QYHOGNECVPUZTFDJAXWMKISRBL", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "UKW", ['A'])

rotor("ETW", "-", "Enigma Z", "1234567890", "1234567890", "ETW", ['1'])
rotor("I", "-", "Enigma Z", "6418270359", "1234567890", "NORMAL", ['9'])
rotor("II", "-", "Enigma Z", "5841097632", "1234567890", "NORMAL", ['9'])
rotor("III", "-", "Enigma Z", "3581620794", "1234567890", "NORMAL", ['9'])
rotor("UKW", "-", "Enigma Z", "5079183642", "1234567890", "UKW", ['1'])